List productData = [
  {
    "videoUrl": "assets/videos/Pet.mp4",
    "productUrl":
        "https://madeubuyit.com/products/pumpkin-self-cleaning-slicker-comb-for-dog-cat-puppy-rabbit-grooming-brush-99422",
    "productName": "PET BRUSH",
    "productDescription": "Pet cleaning brush with easy clean mechanism.",
    "currency": "\$",
    "priceBig": "24",
    "priceSmall": ".99",
    "shipping": "",
    "taxes": "(excl. of taxes)",
    "isLiked": false,
    "likes": "423 K",
    "isSaved": false,
    "saves": "39 K",
    "shares": "16 K",
  },
  {
    "videoUrl": "assets/videos/Toys.mp4",
    "productUrl":
        "https://www.amazon.com/Stairs-Roller-Coaster-Electric-Flashing/dp/B09LC99FTV/",
    "productName": "Duck Roller Coaster",
    "productDescription":
        "Self stair climbing toy duck roller coaster for kids.",
    "currency": "\$",
    "priceBig": "25",
    "priceSmall": ".99",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
  {
    "videoUrl": "assets/videos/Tech1.mp4",
    "productUrl":
        "https://www.amazon.in/NiTHO-DRIVE-RACING-compatible-Switch/dp/B08LFLHXG9",
    "productName": "NiTHO DRIVE PRO RACING WHEEL",
    "productDescription":
        "High performance steering wheel and Spring loaded pedals with Brake and accelerator.",
    "currency": "₹",
    "priceBig": "4365",
    "priceSmall": "",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "1.2 M",
    "isSaved": false,
    "saves": "70 K",
    "shares": "13 K",
  },
  {
    "videoUrl": "assets/videos/Tools1.mp4",
    "productUrl":
        "https://www.distrelec.biz/en/stripax-plus-stripping-and-crimping-tool-5mm-weidmueller-9020000000/p/18055006",
    "productName": "Weidmüller Stripax plus",
    "productDescription":
        "Cutting, stripping and crimping tools for connected wire-end ferrules strips.",
    "currency": "€",
    "priceBig": "307",
    "priceSmall": ".34",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "270 K",
    "isSaved": false,
    "saves": "12 K",
    "shares": "4 K",
  },
  {
    "videoUrl": "assets/videos/Home1.mp4",
    "productUrl":
        "https://www.amazon.com/TOWNEW-Self-Sealing-Self-Changing-Automatic-Activated/dp/B098PKLR75/",
    "productName": "TOWNEW T1 Trash Can",
    "productDescription": "Self-Sealing and Self-Changing 4 Gallon Trash Can.",
    "currency": "\$",
    "priceBig": "124",
    "priceSmall": ".95",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "98 K",
    "isSaved": false,
    "saves": "15 K",
    "shares": "2 K",
  },
  {
    "videoUrl": "assets/videos/Kitchen1.mp4",
    "productUrl":
        "https://viralvariety.com/products/blendr?variant=42620008857848",
    "productName": "ViralVariety - BlendR",
    "productDescription": "Mini-Fast-Portable juice blender.",
    "currency": "\$",
    "priceBig": "65",
    "priceSmall": ".00",
    "shipping": "+ free shipping.",
    "taxes": "(excl. of taxes)",
    "isLiked": false,
    "likes": "2.2 M",
    "isSaved": false,
    "saves": "320 K",
    "shares": "80 K",
  },
  {
    "videoUrl": "assets/videos/Fashion.mp4",
    "productUrl":
        "https://ahujasons.com/product/handloom-pure-pashmina-shawl-as00911338.html",
    "productName": "Ahujasons - Pashmina Shawl",
    "productDescription": "Handloom Pure Pashmina Shawl.",
    "currency": "₹",
    "priceBig": "235000",
    "priceSmall": "",
    "shipping": "+ free shipping.",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "270 K",
    "isSaved": false,
    "saves": "12 K",
    "shares": "4 K",
  },
  {
    "videoUrl": "assets/videos/Gym.mp4",
    "productUrl":
        "https://www.amazon.com/Time-Me-Timer-Countdown-Rechargeable/dp/B09FXM1Z5Q/",
    "productName": "TimeMe Timer",
    "productDescription":
        "Countdown Gym Timer and Stopwatch To Help Track Rest Time While Working Out.",
    "currency": "\$",
    "priceBig": "19",
    "priceSmall": ".99",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
  {
    "videoUrl": "assets/videos/Tech2.mp4",
    "productUrl": "https://store.insta360.com/product/one_x2?c=1164",
    "productName": "Insta360 ONE X2",
    "productDescription": "Standalone 360 degree pocket camera.",
    "currency": "￡",
    "priceBig": "429",
    "priceSmall": ".99",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
  {
    "videoUrl": "assets/videos/Tools2.mp4",
    "productUrl":
        "https://www.amazon.com/Wowstick-Electric-Screwdriver-Cordless-Lithium-ion/dp/B07H27G9NF",
    "productName": "Wowstick 1F+",
    "productDescription": "64 In 1 Cordless Electric Screwdriver.",
    "currency": "\$",
    "priceBig": "52",
    "priceSmall": ".98",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
  {
    "videoUrl": "assets/videos/Home2.mp4",
    "productUrl":
        "https://www.amazon.com/Samsung-Disposal-Hygienic-Cleaning-Household-Handheld-vacuums/dp/B08QZZH76Z/",
    "productName": "Samsung Station Dust Disposal",
    "productDescription":
        "Dust Disposal with Hygienic Cleaning Filter for Household Handheld-vacuums.",
    "currency": "\$",
    "priceBig": "163",
    "priceSmall": ".70",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
  {
    "videoUrl": "assets/videos/Kitchen2.mp4",
    "productUrl": "https://thecrunchcup.com/products/the-crunchcup-xl-intl",
    "productName": "The CrunchCup XL",
    "productDescription":
        "Say goodbye to soggy cereal, The CrunchCup® keeps your cereal crunchy.",
    "currency": "\$",
    "priceBig": "24",
    "priceSmall": ".95",
    "shipping": "",
    "taxes": "(incl. of all taxes)",
    "isLiked": false,
    "likes": "3.1 M",
    "isSaved": false,
    "saves": "120 K",
    "shares": "70 K",
  },
];
